### ISSUE TITLE
Release the code under an open source license

### ISSUE THREAD

**Issue by tobiasvl** [accatyyc/libminesweeper#8]
Hey! This is a really nice library! It'd be even nicer if it had an open source/free software license, so people know what they can do with the games they use your library for!

Something permissive like the MIT license might work for a library like this, or perhaps a "copyleft" license such as the GPL. https://choosealicense.com

**Comment by joelekstrom** [comment]
Hi! Thanks for the suggestion. A license has been added. 👍
